# secrets.toml

[supabase]
url = "https://vjhkrvbddmbvxlixuhnu.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZqaGtydmJkZG1idnhsaXh1aG51Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzA3MDQyNzksImV4cCI6MjA0NjI4MDI3OX0.E6CFVm3jC8ZZmHFU_Rfso6rUKMK8VjXi4I4DVXiFOuM"
